email:
  - name: Nicholas Bayley
    address: nick_bayley@johnlewis.co.uk
template:
  path: C:\Temp\template.html
feed: 
  path: C:\Temp\datafeed.txt
report:
  title: OCCO Check
smtp:
  host: 172.22.200.140
  port: 25